### ISSUE TITLE
can't get full RGB brightness

### ISSUE THREAD

**Issue by J6B** [eliotstocker/Light-Controller#26]
I'm creating a MiLight Wifi simulator on ESP8266 and I figured out that I can't get full brightness network packet.

I mean that the full brightness UDP packet should looks like : 0x4E 0x1B 0x55
But using the slider on RGB panes, I got this one at top level : 0x4E 0x19 0x55

It's missing 2 step of brightness

I'm using a samsung S3 mini (with 4" screen)

@++;
J6B

**Comment by AppLamp-API** [comment]
That is correct. I noticed the same.
Only after retrying one or two  times on the top range you can get to 
the full brightness.
I think it might be due to the UDP package overload, or due a small 
slider on a high rez screen with smaller physical dimensions.
I know it might be a component slider so it is less easy to hack, but 
maybe extending the slider range above 0x1B towards 0x1F and do a 
value.min(slidervalue,0x1B) on the return value might do the magic as it 
gives you more range and space on the slider to reach the max bright 
value (and some extra send 1B commands).

Vriendelijke groet,
Stijn De Ryck
www.applamp.nl <http://www.applamp.nl>
T: +31(0)307370522

[logo] <http://www.applamp.nl>

**Comment by NoonanMedia** [comment]
i can add another tick as the top of the slider and make it send the top value again, do you think that would help?

**Comment by eliotstocker** [comment]
i can add another tick to the top of the slider with another max value on it, perhaps that will solve it?

**Comment by AppLamp-API** [comment]
Vriendelijke groet,
Stijn De Ryck
www.applamp.nl <http://www.applamp.nl>
T: +31(0)307370522

[logo] <http://www.applamp.nl>
you can try :)
Just wonder or it has to do with the slider itself (small phisical 
display+hig res) or with the UDP overload
A delayed tick would be good to test though

**Comment by eliotstocker** [comment]
I changed a couple of small bits of code in the legates beta for this can someone check it for me? I really can't tell haha.

**Comment by eliotstocker** [comment]
Im going to close this, im not 100% sure its fixed but i cant detect any real difference between light controller top brightness and the milight app, let me know if it needs reopening
